### ISSUE TITLE
New tariff system

### ISSUE THREAD

**Issue by suskozaver** [Trzinka/HA-energy-cost#1]
Did you ever expand this solution to the new tariff system we have in Slovenia?

**Comment by Trzinka** [comment]
Pozdravljen.

Nekaj sem se igral a je pre komplicirano ker vsak mesec dobimo drugačen obračun, ker nam elektro spreminja dogovorjeno moč in tudi država pogosto menja način pomoči pri poizkusu znižanaj stroškov.

Tole sem naredil a ne uporabljam (datoteka `sensors.yaml`):
```yaml
#=========================================================================================================================================================
#                          Obračun elektrike
#=========================================================================================================================================================
#============================================
# Cene
#============================================
  - platform: template
    sensors:
      cena_elektricne_energije_et:
        friendly_name_template: "Cena električne energije ET"
        value_template: "0.098000"
        unit_of_measurement: EUR
        unique_id: 9b434ad5-7c23-4d49-8ffa-a30c17e2084a
#============================================
      cena_obracunske_moci:
        friendly_name_template: "Cena obračunske moči"
        value_template: "0.796000"
        unit_of_measurement: EUR
        unique_id: d462bb14-36d7-4d2c-bb04-5cf5f1767b52 

      cena_omreznine_et:
        friendly_name_template: "Cena omrežnine ET"
        value_template: "0.039730"
        unit_of_measurement: EUR
        unique_id: 561a3387-3b86-4f66-97bc-937cb471ee86
#============================================
      cena_prispevka_za_delovanje_operaterja_trga:
        friendly_name_template: "Cena prispevka za delovanje operaterja trga"
        value_template: "0.000130"
        unit_of_measurement: EUR
        unique_id: 0c975325-7cc9-444b-a28a-323a5158aaab

      cena_prispevka_za_energetsko_ucinkovitost:
        friendly_name_template: "Cena prispevka za energetsko učinkovitost"
        value_template: "0.000800"
        unit_of_measurement: EUR
        unique_id: 5cbf3c18-87b3-4373-ab6c-26148c5a8c60

      cena_prispevka_za_spte_in_ove:
        friendly_name_template: "Cena prispevka za SPTE in OVE"
        value_template: "0.000000"
        unit_of_measurement: EUR
        unique_id: 6dc798f8-ba9b-4a9e-8df4-d7449c0bdea5
#============================================
      cena_trosarine:
        friendly_name_template: "Cena trošarine"
        value_template: "0.001530"
        unit_of_measurement: EUR
        unique_id: 5e1bfb3f-d6e2-4f42-b9b9-6789df157e0d
#============================================
      cena_jederske_energije:
        friendly_name_template: "Cena jederske energije"
        value_template: "0.000000"
        unit_of_measurement: EUR
        unique_id: a7d6e709-83d3-4ade-b542-84deca5d761e

      cena_pavsalnih_stroskov:
        friendly_name_template: "Cena pavšalnih stroškov"
        value_template: "1.990000"
        unit_of_measurement: EUR
        unique_id: 980811d4-3c6f-434c-a624-bf24c460dbc1

      cena_e_popusta:
        friendly_name_template: "Cena E-popusta"
        value_template: "0.810000"
        unit_of_measurement: EUR
        unique_id: 06476065-a9e7-40fe-8deb-1e6504a19ada
#============================================
# Vrednost obračunske moči
#============================================ 
      vrednost_obracunske_moci:
        friendly_name_template: "Vrednost obračunske moči"
        value_template: "10"
        unit_of_measurement: kW
        unique_id: bbd15e8b-9fb7-4d7c-b7df-084607f145b4
#============================================
# Količina električne energije na uro
#============================================ 
      kolicina_elektricne_energije_na_uro:
        friendly_name_template: "Količina električne energije na uro"
        value_template: "1072"
        unit_of_measurement: kWh
        unique_id: 755c2329-9455-48f6-883f-4104092e8315      
#============================================
# IZRAČUN
#============================================ 
      skupaj_izracun_stroska_elektricne_energije:
        friendly_name: "Skupaj izračun stroška električne energije"
        value_template: >
          {{ (states('sensor.cena_elektricne_energije_et') | float(default=0)) * (states('sensor.kolicina_elektricne_energije_na_uro') | float(default=0)) }}
        unit_of_measurement: "EUR"
        unique_id: "157cc9e7-fa6b-4961-b971-b2a5107aa273"
#============================================
      izracun_stroska_obracunske_moci:
        friendly_name: "Izračun stroška obračunske moči"
        value_template: >
          {{ (states('sensor.cena_obracunske_moci') | float(default=0)) * (states('sensor.vrednost_obracunske_moci') | float(default=0)) }}
        unit_of_measurement: "EUR"
        unique_id: "05f452bb-be1b-4857-8504-75151ea02a59"

      izracun_stroska_omreznine_et:
        friendly_name: "Izračun stroška omrežnine ET"
        value_template: >
          {{ (states('sensor.cena_omreznine_et') | float(default=0)) * (states('sensor.kolicina_elektricne_energije_na_uro') | float(default=0)) }}
        unit_of_measurement: "EUR"
        unique_id: "327271f4-0606-4665-87d0-4c57fbbf48b3"

      skupaj_izracun_stroska_omreznine_za_elektroenergetski_sistem:
        friendly_name: "Skupaj izračun stroška omrežnine za elektroenergetski sistem"
        value_template: >
          {{ (states('sensor.izracun_stroska_obracunske_moci') | float(default=0)) + (states('sensor.izracun_stroska_omreznine_et') | float(default=0)) }}
        unit_of_measurement: "EUR"
        unique_id: "90bfc447-6e37-430f-b1da-99013f9ba497"
#============================================
      izracun_stroska_prispevka_za_delovanje_operaterja_trga:
        friendly_name: "Izračun stroška prispevka za delovanje operaterja trga"
        value_template: >
          {{ (states('sensor.cena_prispevka_za_delovanje_operaterja_trga') | float(default=0)) * (states('sensor.kolicina_elektricne_energije_na_uro') | float(default=0)) }}
        unit_of_measurement: "EUR"
        unique_id: "01357d12-b7e9-4b21-b54d-022c059a8811"

      izracun_stroska_prispevka_za_energetsko_ucinkovitost:
        friendly_name: "Izračun stroška prispevka za energetsko učinkovitost"
        value_template: >
          {{ (states('sensor.cena_prispevka_za_energetsko_ucinkovitost') | float(default=0)) * (states('sensor.kolicina_elektricne_energije_na_uro') | float(default=0)) }}
        unit_of_measurement: "EUR"
        unique_id: "470278cf-f5b1-4566-b14a-3637e1197bfb"

      izracun_stroska_prispevka_za_spte_in_ove:
        friendly_name: "Izračun stroška prispevka za SPTE in OVE"
        value_template: >
          {{ (states('sensor.cena_prispevka_za_spte_in_ove') | float(default=0)) * (states('sensor.vrednost_obracunske_moci') | float(default=0)) }}
        unit_of_measurement: "EUR"
        unique_id: "c3a77213-c751-496b-998f-8c3b1782c4c3"

      skupaj_izracun_stroska_prispevkov_in_ostalih_dajatev:
        friendly_name: "Skupaj izračun stroška prispevkov in ostalih dajatev"
        value_template: >
          {{ (states('sensor.izracun_stroska_prispevka_za_delovanje_operaterja_trga') | float(default=0)) + (states('sensor.izracun_stroska_prispevka_za_energetsko_ucinkovitost') | float(default=0)) + (states('sensor.izracun_stroska_prispevka_za_spte_in_ove') | float(default=0)) }}
        unit_of_measurement: "EUR"
        unique_id: "620071a0-8057-4cc0-89bd-7e4c9fe3f44f"
#============================================
      skupaj_izracun_stroska_trosarine:
        friendly_name: "Skupaj izračun stroška trošarine"
        value_template: >
          {{ (states('sensor.cena_trosarine') | float(default=0)) * (states('sensor.kolicina_elektricne_energije_na_uro') | float(default=0)) }}
        unit_of_measurement: "EUR"
        unique_id: "c4d265d9-c7ce-478d-9f16-8402d14e61cb"
#============================================
      skupaj_izracun_stroska_storitev_storitev_pogodbenega_racuna:
        friendly_name: "Skupaj izračun stroška storitev pogodbenega računa"
        value_template: >
          {{ (states('sensor.cena_jederske_energije') | float(default=0)) + (states('sensor.cena_pavsalnih_stroskov') | float(default=0)) - (states('sensor.cena_e_popusta') | float(default=0)) }}
        unit_of_measurement: "EUR"
        unique_id: "a15e8c65-ac34-4e68-ba1f-81d2052291e8"          
#============================================
# SKUPAJ IZRAČUN
#============================================
      skupaj_izracun_stroskov:
        friendly_name: "Skupaj izračun stroškov"
        value_template: >
          {{ (states('sensor.skupaj_izracun_stroska_elektricne_energije') | float(default=0)) + (states('sensor.skupaj_izracun_stroska_omreznine_za_elektroenergetski_sistem') | float(default=0)) + (states('sensor.skupaj_izracun_stroska_prispevkov_in_ostalih_dajatev') | float(default=0)) + (states('sensor.skupaj_izracun_stroska_trosarine') | float(default=0)) + (states('sensor.cena_jederske_energije') | float(default=0)) + (states('sensor.cena_pavsalnih_stroskov') | float(default=0)) - (states('sensor.cena_e_popusta') | float(default=0)) }}
        unit_of_measurement: "EUR"
        unique_id: "c88ba7d9-5e8b-467b-bc50-6c1e452f2c8c"
```

Na tak način bi lahko naredil obračun po novem, a bi moral vpisovati podatke, ko prejmeš račun (se pravi obračun za nazaj).

Po pravici povedano se nisem spuščal v sprotni obračun, ker si ga niti teoretično ne predstavljam kako bi ga obračunaval.

Za obračun za nazaj (ko prejmem račun) mi je bilo lažje narediti izračun v Excelovi tabeli (v isti hiši živi še ena družina tako, da imamo poleg električnega števca še odštevalni števec "oba fizična"). Uporabljam pa tudi P1 meter `https://www.homewizard.com/shop/wi-fi-p1-meter/`, ki je priključen na glavni števec in še Shelly Pro 3EM `https://www.shelly.si/si/merilniki-porabe-energije/71-123-shelly-pro-3em-3-fazni-merilnik.html#/41-tokovniki-120_a`, ki je priključen za odštevalnim števcem.
